### ISSUE TITLE
Option to prefer decimal separator

### ISSUE THREAD

**Issue by CvBlixen** [pocketrocket/floatify#8]
In our use case, too big numbers cause more frustration / damage than too small, so I would like an option to prefer decimal instead of thousands separators.

The tests for it could look something like this:

```javascript
  {
    title: 'should optionally prefer decimal separators',
    assertions: [
      {
        input: '123.123',
        options: {preferDecimalSeparators: true},
        expectation: 123.123
      },
      {
        input: '123,123',
        options: {preferDecimalSeparators: true},
        expectation: 123.123
      },
    ]
  },
```

**Comment by pocketrocket** [comment]
@CvBlixen back from vaccay - will have a look into this EoW

**Comment by pocketrocket** [comment]
@CvBlixen please check https://github.com/pocketrocket/floatify/pull/9
